const {Schema,model}=require('mongoose')
const bloodBankSchema=new Schema({
    user:{
        type:Schema.Types.ObjectId,
        ref:'User'
    },
    name:String,
    phoneNumber:String,
    address:{
        building:{
            type:String,
            required:true
         },
         locality:{
             type:String,
             required:true
          },
         city:{
             type:String,
             required:true
          },
         state:{
             type:String,
             required:true
          },
         pincode:{
             type:String,
             required:true
         },
         country:{
             type:String,
             required:true
         }
        },
    geoLocation:{
        type:{
            type:String,
            required:true,
            enum:['Point']
        },
        coordinates: {      
            required:true,
            type:[Number]       
        }
    },
    availableBlood:[],
    openingHours:{
        opensAt:{
            hour:Number,
            minutes:Number,
            period:String
        },
        closesAt:{
            hour:Number,
            minutes:Number,
            period:String
        }
    },
    services:[String],
    license:[{type:String}],
    photos:[{type:String}],
    isApproved:{
    type:String,
    default:'pending'
    }
},{timestamps:true})
const BloodBank=model('BloodBank',bloodBankSchema)
module.exports=BloodBank